"""empty message

Revision ID: f4da50542687
Revises: 0fbbe132e42b
Create Date: 2016-12-15 12:44:58.622845

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4da50542687'
down_revision = '0fbbe132e42b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_reset_token', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password_reset_token')
    # ### end Alembic commands ###
